parameters:
    z00: #cofactor exploration step
        dataloc: '/project/iprime_storage/myles_kim/_Spect_Analysis/_Allcell/_subsample_100k_t'  # data location
        figure_dir: 'figures_for_spectral_cofactor' #figures will be saved here
        cofactorlist: "[1000.0, 2000.0, 5000.0, 8000.0, 10000.0, 12000.0]"     #cofactors to use. have minimum of 6 values
        dataset: "SpectralT"
        plotbysubj: False
        numpool: 10
        savefile_fcs_trimmed: &fcstrimmed 'fcs_df_trimmed.csv.gz' #fcs data with all markers. Not transformed
    z01:   #batch correction
        figure_dir: 'figures_for_batch_correct'
        fcstrimmed: *fcstrimmed #'fcs_df_trimmed.csv.gz' #z00.savefile_fcs_trimmed
        cofactorfile: 'cofactors.csv'
        batchinfo: 'batch.csv'
        numpool: 4
    z02:
        fcsdata: 'fcs_df_cycombine_BCed.csv.gz'
        label: 't_cell_hogan'
        figsavedir: "figures_for_spectral_umap"
        cofactorfile: 'cofactors.csv'
        min_dist: 0.01
    z03:
        label: 't_cell_markers_hogan'
        rp_list: "[round(x*0.05,3) for x in range(2,11)]"    
        figsavedir: "figures_for_spectral_umap"
        min_dist: 0.01
    z04:
        cofactorfile: 'cofactors.csv'
        figure_dir: 'round_one_clustering'